### ISSUE TITLE
error when i run main.py

### ISSUE THREAD

**Issue by Salem-KHIMOUD** [fabiocarrara/deep-parking#1]
Hi sir 
i need your help 
when i compile main.py or pklot.py get some errors " IndexError: list index out of range" and i don't where i must to change 
-----------------------
env :
- ubuntu 16.04
- caffe only cpu, i don't use gpu 

INFO 2018-03-22 10:35:55: Setting up mAlexNet trained on CNRPark-EXT_camera1, validated on PKLot_val, CNRPark-EXT_camera2, CNRPark-EXT_camera3, CNRPark-EXT_camera4, CNRPark-EXT_camera5, CNRPark-EXT_camera6, CNRPark-EXT_camera7, CNRPark-EXT_camera8, CNRPark-EXT_camera9, tested on PKLot_test_CNRPark-EXT_camera2_CNRPark-EXT_camera3_CNRPark-EXT_camera4_CNRPark-EXT_camera5_CNRPark-EXT_camera6_CNRPark-EXT_camera7_CNRPark-EXT_camera8_CNRPark-EXT_camera9 ...
INFO 2018-03-22 10:35:56: Training on CNRPark-EXT_camera1 while validating on PKLot_val, CNRPark-EXT_camera2, CNRPark-EXT_camera3, CNRPark-EXT_camera4, CNRPark-EXT_camera5, CNRPark-EXT_camera6, CNRPark-EXT_camera7, CNRPark-EXT_camera8, CNRPark-EXT_camera9 ...
DEBUG 2018-03-22 10:35:56: Summarizing mAlexNet-tr_PKLot_train-vl_PKLot_val_CNRPark-EXT_val-ts_PKLot_test_CNRPark-EXT_test ...
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    pyffe.summarize(exps).to_csv('results.csv')
  File "/home/pret/Bureau/deep-parking/pyffe/experiment.py", line 89, in summarize
    r = e.summarize()
  File "/home/pret/Bureau/deep-parking/pyffe/experiment.py", line 46, in decorator
    return function(*args, **kwargs)
  File "/home/pret/Bureau/deep-parking/pyffe/experiment.py", line 558, in summarize
    last_iter = log_data['train']['iteration'][-1]
IndexError: list index out of range

Thanks sir 
i wish you the best 
good luck

**Comment by fabiocarrara** [comment]
It seems the created folders for the experiments do not contain the training log. Probably the caffe invocation has failed and has not produced any training information.
Please try to remove the `runs` folder, check that the invocation to `caffe` works, and run again the main script.

**Comment by Salem-KHIMOUD** [comment]
it's another result but with same error 

INFO 2018-03-22 11:41:24: Setting up mAlexNet trained on CNRPark-EXT_camera1, validated on PKLot_val, CNRPark-EXT_camera2, CNRPark-EXT_camera3, CNRPark-EXT_camera4, CNRPark-EXT_camera5, CNRPark-EXT_camera6, CNRPark-EXT_camera7, CNRPark-EXT_camera8, CNRPark-EXT_camera9, tested on PKLot_test_CNRPark-EXT_camera2_CNRPark-EXT_camera3_CNRPark-EXT_camera4_CNRPark-EXT_camera5_CNRPark-EXT_camera6_CNRPark-EXT_camera7_CNRPark-EXT_camera8_CNRPark-EXT_camera9 ...
INFO 2018-03-22 11:41:26: Training on CNRPark-EXT_camera1 while validating on PKLot_val, CNRPark-EXT_camera2, CNRPark-EXT_camera3, CNRPark-EXT_camera4, CNRPark-EXT_camera5, CNRPark-EXT_camera6, CNRPark-EXT_camera7, CNRPark-EXT_camera8, CNRPark-EXT_camera9 ...
I0322 11:41:26.872061  9729 upgrade_proto.cpp:1084] Attempting to upgrade input file specified using deprecated 'solver_type' field (enum)': solver.prototxt
I0322 11:41:26.872313  9729 upgrade_proto.cpp:1091] Successfully upgraded file specified using deprecated 'solver_type' field (enum) to 'type' field (string).
W0322 11:41:26.872323  9729 upgrade_proto.cpp:1093] Note that future Caffe releases will only support 'type' field (string) for a solver's type.
I0322 11:41:26.872442  9729 caffe.cpp:204] Using GPUs 0
F0322 11:41:26.872454  9729 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
    @     0x7f2d273845cd  google::LogMessage::Fail()
    @     0x7f2d27386433  google::LogMessage::SendToLog()
    @     0x7f2d2738415b  google::LogMessage::Flush()
    @     0x7f2d27386e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2d27709ea0  caffe::Caffe::SetDevice()
    @           0x40a4eb  train()
    @           0x406fa0  main
    @     0x7f2d262f4830  __libc_start_main
    @           0x4077c9  _start
    @              (nil)  (unknown)
DEBUG 2018-03-22 11:41:27: Summarizing mAlexNet-tr_PKLot_train-vl_PKLot_val_CNRPark-EXT_val-ts_PKLot_test_CNRPark-EXT_test ...
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    pyffe.summarize(exps).to_csv('results.csv')
  File "/home/pret/Bureau/deep-parking/pyffe/experiment.py", line 86, in summarize
    r = e.summarize()
  File "/home/pret/Bureau/deep-parking/pyffe/experiment.py", line 44, in decorator
    return function(*args, **kwargs)
  File "/home/pret/Bureau/deep-parking/pyffe/experiment.py", line 550, in summarize
    last_iter = log_data['train']['iteration'][-1]
IndexError: list index out of range

**Comment by fabiocarrara** [comment]
In the `pyffe` module, the use of the GPU is hardcoded in the following locations:

https://github.com/fabiocarrara/pyffe/blob/d07a39a1d239edee5db972be8b88d5802fdf17ec/experiment.py#L244

https://github.com/fabiocarrara/pyffe/blob/d07a39a1d239edee5db972be8b88d5802fdf17ec/experiment.py#L392

https://github.com/fabiocarrara/pyffe/blob/d07a39a1d239edee5db972be8b88d5802fdf17ec/experiment.py#L454

You need to change those lines removing the '-gpu 0' flags.
Please refer to the [caffe documentation](http://caffe.berkeleyvision.org/tutorial/interfaces.html).
Add also `solver_mode=0` to the `pyffe.Solver` definition in the `main.py` file.

**Comment by Salem-KHIMOUD** [comment]
thanks sir until now [program](url) working 
sir i can make test with my pictures 
if i would to do test what i must to do 
thanks sir ;)
![image](https://user-images.githubusercontent.com/33195125/37775114-5680e288-2de2-11e8-947d-489799200d65.png)
