### ISSUE TITLE
pyffe folder is empty when cloning

### ISSUE THREAD

**Issue by shubhamnagalwade** [fabiocarrara/deep-parking#10]
Hi,
When i download or clone the git it is not properly work. pyffe folder is empty.

**Comment by fabiocarrara** [comment]
Hi, you have to clone with the `--recursive` flag.

A simple Google search: https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by shubhamnagalwade** [comment]
Hi,
Thank you. I will try.
