### ISSUE TITLE
Cannot use GPU in CPU-only Caffe: check mode.

### ISSUE THREAD

**Issue by FDZero** [fabiocarrara/deep-parking#16]
HI，when i run 'python main.py'
it throw a question ' Cannot use GPU in CPU-only Caffe: check mode.'

root@linaro-alip:/usr/local/deeppark# python deep-parking/main.py
INFO 2019-08-15 07:15:10: Setting up mAlexNet trained on PKLot_train, validated on PKLot_val, CNRPark-EXT_val, tested on PKLot_test_CNRPark-EXT_test ...
INFO 2019-08-15 07:15:14: Training on PKLot_train while validating on PKLot_val, CNRPark-EXT_val ...
I0815 07:15:14.889346 16789 upgrade_proto.cpp:1084] Attempting to upgrade input file specified using deprecated 'solver_type' field (enum)': solver.prototxt
I0815 07:15:14.890483 16789 upgrade_proto.cpp:1091] Successfully upgraded file specified using deprecated 'solver_type' field (enum) to 'type' field (string).
W0815 07:15:14.890511 16789 upgrade_proto.cpp:1093] Note that future Caffe releases will only support 'type' field (string) for a solver's type.
I0815 07:15:14.891098 16789 caffe.cpp:204] Using GPUs 0
F0815 07:15:14.891127 16789 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
    @ 0xb6cc9e2e  google::LogMessage::Fail()
    @ 0xb6ccb42a  google::LogMessage::SendToLog()
    @ 0xb6cc9adc  google::LogMessage::Flush()
    @ 0xb6ccba4c  google::LogMessageFatal::~LogMessageFatal()
    @ 0xb6e2a82c  caffe::Caffe::SetDevice()
    @ 0x7f5cbc62  train()
    @ 0x7f5c90ca  main
    @ 0xb5af54aa  __libc_start_main

**Comment by fabiocarrara** [comment]
Unfortunately, GPU usage is hardcoded and is tricky to disable.
Try changing the device to CPU in the solver initialization in Pyffe by changing this line

https://github.com/fabiocarrara/pyffe/blob/be98c54449ff4240c922714a53fc6bb8f0319c82/solver.py#L61

from:

self.sp.solver_mode = 1  # GPU

to:

self.sp.solver_mode = 0 

You need also to remove the '-gpu 0' flags in the invocations to 'caffe' and 'extract_features' in:

https://github.com/fabiocarrara/pyffe/blob/be98c54449ff4240c922714a53fc6bb8f0319c82/experiment.py

on lines 244, 392, and 454.

**Comment by FDZero** [comment]
Thanks ，follow your method ，i solved current problem 
Next, I will study your code, try to understand how it works and train the model.
