### ISSUE TITLE
How to use the camera

### ISSUE THREAD

**Issue by FDZero** [fabiocarrara/deep-parking#18]
Hi, i have successed run 'python main.py' on Debian9.
Next step ,i don't kown how to use the camera , i have saw the online video in ‘http://cnrpark.it/’, in the video , how can i present the same picture in the video？

**Comment by fabiocarrara** [comment]
Everything you need to deploy your system (e.g. opening the camera, grabbing frames, segmenting parking spaces, feed the model, draw predictions on the frame, and build a video) is not implemented here.
As already stated (see #17), this repo that is uniquely dedicated to reproducing the paper's experiments.
