### ISSUE TITLE
where to download the raw image / video of "CNRPark" and "CNR-EXT" dataset

### ISSUE THREAD

**Issue by amiltonwong** [fabiocarrara/deep-parking#2]
Hi, @fabiocarrara ,

I'm very interested in your work "Deep learning for decentralized parking lot occupancy detection", and would like to study it further and for practicing the detection. For detection evaluation on the parking lots, I could see the evaluation [video ](https://www.youtube.com/watch?time_continue=1&v=HnJYSWY60nA), where could I download the raw image / video dataset? I had downloaded the "CNRPark" and "CNR-EXT" dataset, but only segmented patches located inside and there's no any raw image (with the view on the parking ground) or video in it. 

I'd like to download the raw image / video. Could you help me ?

Thanks!

**Comment by fabiocarrara** [comment]
Due to privacy issues, we are allowed to distribute only a lower-resolution version of the camera frames. Those are now available at: http://cnrpark.it
