### ISSUE TITLE
Not Issue: Request for tutorial to setup, load and use existing model from zero on RasberryPi

### ISSUE THREAD

**Issue by gauravdhiman** [fabiocarrara/deep-parking#4]
@fabiocarrara - Your project is impressive. I would like to explore more. Need to know the steps to setup, load and use your existing model of mAlexNet on RasberryPi.

Can you please write a detailed article / blog / README to explain, how to setup, load and use you models on RasberryPi + camera, so that we can see the things in action by pointing camera to some parking lot.

Another query - Do make the model work, do we need to mark the parking lots manually or the CNN automatically identifies the parking space (patch) by itself in whole picture of parking lot ?

**Comment by fabiocarrara** [comment]
Hi @gauravdhiman ,
I will probably write a brief guide as a wiki article in this repo.
In the meantime, the procedure can be broken down into those two steps:
- installing caffe + python on the Raspberry Pi: (you can follow [this guide](http://www.knight-of-pi.org/deepdreaming-on-a-raspberry-pi-2/) until *Protobuf installation* excluded)
- make a prediction with a caffe model using the pycaffe interface (there are lots of tutorial on this, e.g. [link](http://christopher5106.github.io/deep/learning/2015/09/04/Deep-learning-tutorial-on-Caffe-Technology.html))

About the parking spaces, you need to manually segment the camera frame to extract the patches of the single spaces and feed them to the network.
