### ISSUE TITLE
Not an Issue - request to share input image preprocessing parameters for using the pretrained models

### ISSUE THREAD

**Issue by manoj652** [fabiocarrara/deep-parking#6]
Hi Fabio,
Very impressive work on this project. I wanted to know the input image preprocessing parameters for the blob creation to use your Alexnet.

**Comment by fabiocarrara** [comment]
Hi @manoj652 ,
our networks are fed with 224 x 224 BGR images (ala OpenCV) with pixel values in the range [0,1] (we divide all pixel values by 255). In our experiments, we first resize the image to 256 x 256 and then obtain a 224 x 224 crop (random crop when training, central crop when evaluating).
