### ISSUE TITLE
mean.binaryproto file ambiguity

### ISSUE THREAD

**Issue by FrancescoBoi** [fabiocarrara/deep-parking#9]
I am looking at the model CNRPark-Trained-Models/mAlexNet-on-CNRPark.

It contains the file `mean.binaryproto`. Loading this file in Python I see it is an array of dimensions: 3x256x256. Does it contain the means of each pixel for all the three channels? If not how to interpret it?

Are the channels in the RGB or BGR format? I could not find any description of it.

It is better in my opinion to save the means in another format since there might be compatibility issues when importing in other frameworks rather than caffe: OpenCV in C++ can load the `caffemodel` and `proto` files but not the mean file `mean.binaryproto`.

Any help will be appreciated.

**Comment by fabiocarrara** [comment]
The zip files have been generated by DIGITS and thus can be imported easily in DIGITS again.
DIGITS relies on Caffe helper binaries, thus the mean file conforms with the format usually adopted by Caffe models: it's a BGR mean image (each pixel is the mean pixel over the training set).

This mean file is automatically included in the zip file when exporting the model to zip file with DIGITS.
However, **we did not use mean subtraction when training our models**. Thus, you can ignore that file if you want to reproduce our experiments or deploy our trained network.

For completeness, [here](https://github.com/BVLC/caffe/issues/290) you can find how to convert binaryproto files to numpy or other Python-friendly formats by using the pyCaffe interface.

**Comment by FrancescoBoi** [comment]
So it is the array containing the mean for each pixel and no mean subtraction has been performed on the training set but the file was automatically generated.

Thank you so much for you quick reply and clarification.
Kind regards
